[preface]
== Glossário Rápido


Esse glossário rápido contém muitos dos termos usados em relação ao bitcoin. Esses termos são usados em todo o livro, então favorite isso para uma referência rápida

endereço (address)::
    Um endereço (address) bitcoin parece com +1DSrfJdB2AnWaFNgSbv3MZC2m74996JafV+. Consiste de uma string de letras e números começando com um "1" (número um). Assim como você pede aos outros para enviar um e-mail para o seu endereço de e-mail, você irá pedir aos outros para lhe enviar bitcoin para o seu endereço bitcoin.((("bitcoin address")))((("address", see="bitcoin address")))((("public key", see="bitcoin address")))

bip::
    Proposta de melhoria do Bitcoin (Bitcoin Improvement Proposals). Um conjunto de proposta que membros da comunidade de bitcoin submete para melhorar o bitcoin. Por exemplo, BIP0021 e uma proposta para melhorar o esquema do identificador de endereços na internet (URI) do bitcoin.((("bip")))

bitcoin::
    O nome da unidade monetária (A moeda), a rede e o software.((("bitcoin")))

block::
    Um agrupamento das transações, marcado com um timestamp, e uma impressão digital do bloco anterior. O cabeçalho do bloco é um hash para produzir uma prova de trabalho, assim validando as transações. Blocos válidos são adicionados ao blockchain principal por consenso da rede.((("block")))

blockchain::
  Uma lista de blocos validados, cada um ligando ao seu antecessor até o bloco gênese.((("blockchain")))

confirmações (confirmations)::
  Uma vez que uma transação é incluída em um bloco, ela tem uma confirmação. Assim que _outro_ bloco é minerado no mesmo blockchain, a operação tem duas confirmações, e assim por diante. Seis ou mais confirmações é considerado prova suficiente de que a transação não pode ser revertida.((("confirmations")))

Dificuldade (difficulty)::
  Uma configuração de toda a rede que controla a quantidade de computação que é requirido para produzir uma prova de trabalho.((("difficulty")))

Dificuldade alvo (difficulty target)::
 	Uma dificuldade no qual a computação da rede ira encontrar blocos aproximadamente a cada 10 minutos.((("target difficulty")))

difficulty retargeting::
	Um recálculo feito pela rede da dificuldade, que ocorre uma vez a cada 2.106 blocos e considera o poder de hash dos 2.106 blocos anteriores.((("difficulty retargeting")))

fees::
  O remetente de uma operação muitas vezes inclui uma taxa para a rede para o processamento da transação solicitada. A maioria das transações exigem uma taxa mínima de 0,5 MBTC.((("fees")))

hash::
  Uma impressão digital de alguma entrada binária.((("hash")))

bloco gênese (genesis block)::
  O primeiro bloco no blockchain, usado para inicializar a crypto moeda.((("genesis block")))

minerador (miner)::
  Um nó da rede que encontra prova válida de trabalho para novos blocos, por hashing repetida.((("miner")))

rede (network)::
  Uma rede peer-to-peer que propaga transações e blocos para cada nó bitcoin na rede.((("network")))

prova de Trabalho (Proof-Of-Work)::
  Um pedaço de dados que requer computação significativa para se encontrar. Em bitcoin, os mineradores devem encontrar uma solução numérica para o algoritmo SHA256 que respeite o objectivo de toda a rede, a dificuldade alvo.((("proof-of-work")))

recompensa (reward)::
  Um montante incluído em cada novo bloco como uma recompensa pela rede para o minerador que encontrou a solução da prova de trabalho. É atualmente 25BTC por bloco.((("reward")))

chave secreta (secret key ou private key)::
  O número secreto que desbloqueia bitcoins enviados para o endereço correspondente. A chave secreta parece com +5J76sF8L5jTtzE96r66Sf8cka9y44wdpJjMwCxR3tzLh3ibVPxh+.((("secret key")))((("private key", see="secret key")))

transação (transaction)::
  Em termos simples, uma transferência de bitcoins de um endereço para outro. Mais precisamente, uma transação é uma estrutura de dados assinados expressando uma transferência de valor. As transações são transmitidos através da rede bitcoin, recolhido pelos mineradores, e incluídos em blocos, tornada permanente no blockchain.((("transaction")))

Carteira (wallet)::
  Software que mantém todos os seus endereços bitcoin e chaves secretas. Use-o para enviar, receber e armazenar o seu bitcoin.((("wallet")))